# Generated by Django 4.2 on 2025-03-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_comment_movie_id_comment_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='quoted_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='movies.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movies.comment'),
        ),
    ]
