# Generated by Django 5.2.1 on 2025-06-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_categories_movie_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='movies.movie')),
            ],
        ),
    ]
