# Generated by Django 6.0.4 on 2026-06-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_genre_alter_category_options_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
